### ISSUE TITLE
PR curves and F-measure curves

### ISSUE THREAD

**Issue by WkangLiu** [monxxcn/TSERNet#1]
Nice work, but I have a question while reading, how did you make your PR curves and F-measure curves, looking forward to your reply!

**Comment by monxxcn** [comment]
use this code in Matlab to plot the PR curves and F-measure curves


| |
hcj
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 03/22/2023 15:00 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [monxxcn/TSERNet] PR curves and F-measure curves (Issue #1) |

Nice work, but I have a question while reading, how did you make your PR curves and F-measure curves, looking forward to your reply!

**Comment by WkangLiu** [comment]
> use this code in Matlab to plot the PR curves and F-measure curves | | hcj | | ***@***.*** |
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 03/22/2023 15:00 | | To | ***@***.***> | | Cc | ***@***.***> | | Subject | [monxxcn/TSERNet] PR curves and F-measure curves (Issue #1) | Nice work, but I have a question while reading, how did you make your PR curves and F-measure curves, looking forward to your reply! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thank you！！
